### ISSUE TITLE
cannot load @angular/material

### ISSUE THREAD

**Issue by KevinMind** [codediodeio/angular-firestarter#13]
I've tried following https://material.angular.io instructions. I get one of two errors:

1. app runs with ng serve but material components render as naked html elements.
<button md-button>click me</button> looks like a plane html button

2. the app does not load because "md component is not a known element in angular"

trying out from a fresh clone. Have you run into this before?

**Comment by Steven-Harris** [comment]
ensure you followed all the steps [here](https://material.angular.io/guide/getting-started).

and your are importing the component your trying to use into your module

**Comment by KevinMind** [comment]
I was only importing components to app.module and ui.module. 
I imported to the specific module I wanted a component on and it worked.

**Comment by Steven-Harris** [comment]
@KevinMind, Glad you figured it out.  Please close this is issue when you can.
