### ISSUE TITLE
Cant get access to Items!

### ISSUE THREAD

**Issue by MrExpert** [codediodeio/angular-firestarter#14]
cant get access to items.
running on my localhost:4200
clicking on Connect Anonymously but nothing happening?
please help.
Thanks.

**Comment by codediodeio** [comment]
Have you included the environment.ts files with your Firebase credentials in the project? Please include any errors you get in the console.

**Comment by MrExpert** [comment]
It is Working now. it was firebase Authentication setting needed to be configured.
Great repo. Thank you!
