### ISSUE TITLE
cannot bind 'upload' since it isn't a known property of 'upload-detail

### ISSUE THREAD

**Issue by KevinMind** [codediodeio/angular-firestarter#16]
Can't bind to 'upload' since it isn't a known property of 'upload-detail'.
1. If 'upload-detail' is an Angular component and it has 'upload' input, then verify that it is part of this module.
2. If 'upload-detail' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

<div *ngFor="let upload of uploads | async">
  <upload-detail [ERROR ->][upload]='upload'></upload-detail>
</div>

I have not changed anything in the upload components or service. 
All I did was include the <upload-list> component in the <item-form> component in order to display an upload form along with an item.

It breaks the app though at 

div *ngFor="let upload of uploads | async">
  <upload-detail [upload]='upload'></upload-detail>
</div>

[upload]="upload" is not being recognized for some reason.

REPO: https://github.com/KevinMind/home-inventory-app-official

**Comment by codediodeio** [comment]
Uploads are organized as a feature module, so you can't use uploads with items. However, you can add the components you need to the `exports` section of the upload module to use them in other ngmodules. Reach out on slack if want to take about it more - you will get a much faster response there.
