### ISSUE TITLE
failed on ng serve

### ISSUE THREAD

**Issue by benja-admin** [codediodeio/angular-firestarter#17]
literally followed the readme and fails on ng serve. 
[npm-debug.log](https://github.com/codediodeio/angular-firestarter/files/1334677/npm-debug.log)

**Comment by codediodeio** [comment]
I just made some updates to the dependencies that should fix the issue. Try cloning the latest version and let me know if the problem continues. Also, make sure you have NodeJS and NPM installed on your system.

**Comment by YourSeat** [comment]
followed the same steps and I'm experiencing the same issue. error below:

**Comment by eddwo1** [comment]
Also experiencing this problem with latest version of your repository.
TypeError: Cannot read property 'length' of undefined
    at createSourceFile C:\([...]\angular-firestarter\node_modules\typescript\lib\typescript.j
s:15457:109)

**Comment by brianGammon** [comment]
@eddwo1 Make sure you created the environments/environment.ts file. If it's missing you'll get that error message.
