### ISSUE TITLE
Not working with latest updates

### ISSUE THREAD

**Issue by mayankkalbhor** [codediodeio/angular-firestarter#2]
When i installed angularfire2 and firebase in package.json its not working

ERROR in C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/src/app/core/auth.service.ts (2,10): Module '"C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/node_modules/angularfire2/index"' has no exported member 'AngularFireAuth'.

ERROR in C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/src/app/core/auth.service.ts (2,27): Module '"C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/node_modules/angularfire2/index"' has no exported member 'AngularFireDatabase'.

ERROR in C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/src/app/core/auth.service.ts (2,48): Module '"C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/node_modules/angularfire2/index"' has no exported member 'FirebaseAuthState'.

ERROR in C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/src/app/core/auth.service.ts (2,67): Module '"C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/node_modules/angularfire2/index"' has no exported member 'AuthProviders'.

ERROR in C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/src/app/core/auth.service.ts (2,82): Module '"C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/node_modules/angularfire2/index"' has no exported member 'AuthMethods'.

ERROR in C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/src/app/core/auth.service.ts (2,95): Module '"C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/node_modules/angularfire2/index"' has no exported member 'AngularFire'.

ERROR in C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/src/app/items/shared/item.service.ts (2,10): Module '"C:/Users/mayank.dilip.kalbhor/Desktop/Apps/firestarter/node_modules/angularfire2/index"' has no exported member 'AngularFire'.

Getting many errors. If i run as is after cloning i get the below:

ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken',

Not sure how to clone and run this starter kit

**Comment by codediodeio** [comment]
I just updated the project to AngularFire2 rc4.0.0, which as several significant changes. The packages  are now modular, so you will user `AngularFireAuth` or `AngularFireDatabase`, as opposed to `AngularFire`. Pull the latest version and it should work now. 

Chck out this page from the AngularFire2 docs:
https://github.com/angular/angularfire2/blob/master/docs/version-4-upgrade.md

**Comment by mayankkalbhor** [comment]
Thanks for this. I was fixing it manually but thanks for doing it and also pointing to the actual documentation. The above issue is resolved.
