### ISSUE TITLE
The live demo is not working anymore

### ISSUE THREAD

**Issue by FelipeFelizardo** [codediodeio/angular-firestarter#20]
Could you guys please fix it?

**Comment by caesss** [comment]
Felipe what part is not working for you?

**Comment by FelipeFelizardo** [comment]
this link https://firestarter-96e46.firebaseapp.com/ just shows me "~$ bootstrapping firestarter..."

**Comment by codediodeio** [comment]
@FelipeFelizardo Can you post  screenshot of what you see in chrome dev tools console? The demo seems to be working on my browser/mobile devices.
