### ISSUE TITLE
Would like to see the json data in the realtime database

### ISSUE THREAD

**Issue by eli1797** [codediodeio/angular-firestarter#21]
It would be helpful for us beginners if the data in the realtime database was exported and placed in this repository for future reference.

**Comment by dleonard00** [comment]
You can accomplish this by setting up your own instance of the project adding data to it and then exporting your realtime database. 

The data on the demo version of this app will forever be changing since it's used as a demo and anyone on the internet can access it.

**Comment by codediodeio** [comment]
I am going to improve the docs with some screenshots from Firebase. Not exactly what you asked for, but it will clear up this issue.
