### ISSUE TITLE
The live demo - service worker error

### ISSUE THREAD

**Issue by marcinsydor** [codediodeio/angular-firestarter#22]
That's what I see in the console:
```The script has an unsupported MIME type ('text/html').
/service-worker.js Failed to load resource: net::ERR_INSECURE_RESPONSE
(index):41 SW error DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').
core.es5.js:2925 Angular is running in the development mode. Call enableProdMode() to enable the production mode.```

**Comment by dolebas** [comment]
![image](https://user-images.githubusercontent.com/27515901/31900549-0cde36a0-b81f-11e7-87f4-a0310df8c1c1.png)

**Comment by codediodeio** [comment]
Thank you for brining this to my attention. I am going to merge some updates later this week that will address it.

**Comment by dolebas** [comment]
Great, keep up the good work!

**Comment by codediodeio** [comment]
This issue should be fixed now there was a problem with the worker on the last deploy.
