### ISSUE TITLE
ERROR in TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by AntonPostelnyak** [codediodeio/angular-firestarter#35]
Hello. Download your project and get this error ERROR in TypeError: Cannot read property 'length' of undefined . I can not start the project, I alone have such a problem?
Thank you !
Anton.

**Comment by codediodeio** [comment]
This will happen if you have not created the environment files with your firebase config. Make sure to create the environment files.

**Comment by AntonPostelnyak** [comment]
Sorry, it works, thanks!
