### ISSUE TITLE
Solved: SW error TypeError

### ISSUE THREAD

**Issue by TheMuyu** [codediodeio/angular-firestarter#37]
**Solved**.
i've downloaded files and followed the readme file.
when i run "ng serve" and console says this. 

**SW error TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.**

```
<script>
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/service-worker.js')
      .then((registration) => {
        console.log('SW registered');
      })
      .catch((err) => {
        console.log('SW error', err);
      });
    }
  </script>
```

**Comment by arjunyel** [comment]
Service workers only work with HTTPS while ng serve is just regular HTTP

**Comment by TheMuyu** [comment]
Actually this issue solved
first as you said must be on https.
and after all must be run "npm run pwa" in console. then deploy to firebase.

**Comment by arjunyel** [comment]
@TheMuyu You can mark the issue closed instead of changing the title :) Also if you are just starting  with Firestarter consider starting with my branch that will hopefully get merged soon: https://github.com/arjunyel/angular-firestarter/tree/strict
