### ISSUE TITLE
File list : permission_denied

### ISSUE THREAD

**Issue by ac3ju** [codediodeio/angular-firestarter#41]
Hi,
I can upload files, but I can't get the file list : 
Rules :
`service firebase.storage {
match /b/{bucket}/o {
match /{allPaths=**} {
   allow read, write: if true;
  }
 }
}`

`util.js:189 FIREBASE WARNING: Exception was thrown by user callback. Error: permission_denied at /uploads: Client doesn't have permission to access the desired data.`

`ERROR Error: permission_denied at /uploads: Client doesn't have permission to access the desired data.`

**Comment by codediodeio** [comment]
This was a temporary rules issue with the bucket. Works now.
