### ISSUE TITLE
ERROR in src/app/core/auth.service.ts(48,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.

### ISSUE THREAD

**Issue by DevJoseWeb** [codediodeio/angular-firestarter#61]
not working !
ℹ ｢wdm｣: Failed to compile.
^C
paula@notebook:~/Documentos/angular-firestarter$ ng build

Date: 2018-06-23T03:52:16.493Z
Hash: 520950f4a857e8f82be9
Time: 14104ms
chunk {main} main.js, main.js.map (main) 633 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 688 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 215 kB [initial] [rendered]

ERROR in src/app/core/auth.service.ts(48,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(53,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(58,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(63,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(115,29): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.

**Comment by aashish-ak** [comment]
I tried copying the code and getting same error, but when i'm running the app using npm install after git clone, the app runs fine.

**Comment by DevJoseWeb** [comment]
"  tried copying the code and getting same error, but when i'm running the app using npm install after git clone, the app runs fine. "

I'll try to do !

**Comment by aashish-ak** [comment]
It's not updated with latest version of firebase and angularfire2, you can downgrade the version of firebase to 5.0.2 and of angularfire2 to 5.0.0rc-9.

**Comment by axis80** [comment]
I believe I may have fixed this, by copying the implementation example from the angularfire2 docs, which can be found at https://github.com/angular/angularfire2/blob/master/docs/auth/getting-started.md .

I added this import:

`import { auth } from 'firebase';`

and I changed the `firebase.auth` references to the following:

const provider = new auth.GoogleAuthProvider();
const provider = new auth.GithubAuthProvider();
const provider = new auth.FacebookAuthProvider();
const provider = new auth.TwitterAuthProvider();

**Comment by biranchi2018** [comment]
Yes it worked for me too...

**Comment by lubzey** [comment]
This worked great for the login functions but I still get the error for the resetPassword one:
**ERROR in src/app/core/auth.service.ts(113,29): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.**

**Comment by codediodeio** [comment]
Fixed :)

**Comment by leejend** [comment]
can anyone assist with this error?

ERROR in src/app/auth.service.ts(67,114): error TS2339: Property 'questionId' does not exist on type 'Object'.
src/app/auth.service.ts(75,26): error TS2339: Property 'questionId' does not exist on type 'Object'.
src/app/components/build-script/build-script.component.ts(53,7): error TS2554: Expected 3 arguments, but got 1.
