### ISSUE TITLE
npm run build:all error

### ISSUE THREAD

**Issue by jrodl3r** [codediodeio/angular-firestarter#64]
When I run the `npm run build:all` command I get the following error:

```
> webpack --config webpack.prerender.config.js
Hash: 9b23340b1f8a9397ac3d
Version: webpack 4.6.0
Time: 38ms
Built at: 2018-07-04 12:27:11

ERROR in Entry module not found: Error: Can't resolve './prerender.ts' in '/Users/x/Sites/firestarter'
```

**Comment by codediodeio** [comment]
The prerender script does not exist in the public repo, you can find the code on this page https://angularfirebase.com/lessons/angular-6-universal-ssr-prerendering-firebase-hosting/
