### ISSUE TITLE
FirebaseNamespace

### ISSUE THREAD

**Issue by DevJoseWeb** [codediodeio/angular-firestarter#65]
// Sends email allowing user to reset password
  resetPassword(email: string) {
    const fbAuth = firebase.auth();

ERROR in src/app/core/auth.service.ts(48,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(53,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(58,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(63,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(115,29): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.

ℹ ｢wdm｣: Failed to compile.

**Comment by schankam** [comment]
Duplicate of #61

**Comment by DevJoseWeb** [comment]
Tanks  schankam !
