### ISSUE TITLE
snapshot.bytesTransferred & snapshot.totalBytes not working

### ISSUE THREAD

**Issue by ShafiqEssani** [codediodeio/angular-firestarter#9]
![image](https://user-images.githubusercontent.com/24293253/28959627-afe8f1b8-7914-11e7-8c11-f61d476bce2f.png)

Please check the attached image.
2. The arrow function is also not working.

**Comment by codediodeio** [comment]
Thank you. I just pushed a fix for this that you can check out here https://github.com/codediodeio/angular-firestarter/commit/dd3ce5bc9e596d2367e13f20e4a1ac573f0d8e31#diff-12900559931441d5e97435192e24520a
